import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const network = await ethers.provider.getNetwork();
  const networkName = network.name === "unknown" ? "Base Mainnet" : network.name;
  const chainId = network.chainId.toString();

  console.log("=".repeat(60));
  console.log(`Deploying Game2048 contract to ${networkName} (Chain ID: ${chainId})`);
  console.log("=".repeat(60));

  const [deployer] = await ethers.getSigners();
  console.log("\nDeploying contracts with account:", deployer.address);
  
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH");

  if (chainId === "8453") {
    console.log("\n⚠️  WARNING: Deploying to Base Mainnet!");
    console.log("   Make sure you have enough ETH for gas fees.");
  }

  console.log("\nDeploying contract...");
  const Game2048 = await ethers.getContractFactory("Game2048");
  const game2048 = await Game2048.deploy();

  await game2048.waitForDeployment();

  const address = await game2048.getAddress();
  
  console.log("\n" + "=".repeat(60));
  console.log("✅ Deployment Successful!");
  console.log("=".repeat(60));
  console.log("\nContract address:", address);
  console.log("Network:", networkName);
  console.log("Deployer address:", deployer.address);

  // Save contract address to .env
  const envPath = path.join(__dirname, "../.env");
  let envContent = "";
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, "utf-8");
  }
  
  if (envContent.includes("GAME2048_CONTRACT_ADDRESS=")) {
    envContent = envContent.replace(
      /GAME2048_CONTRACT_ADDRESS=.*/g,
      `GAME2048_CONTRACT_ADDRESS=${address}`
    );
  } else {
    envContent += `\nGAME2048_CONTRACT_ADDRESS=${address}\n`;
  }
  
  fs.writeFileSync(envPath, envContent);
  console.log(`\n✅ Contract address saved to .env`);

  // Export ABI and address to frontend
  const artifactsPath = path.join(__dirname, "../artifacts/contracts/Game2048.sol/Game2048.json");
  const outputPath = path.join(__dirname, "../../frontend/lib/game2048.ts");
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(artifactsPath)) {
    console.error("\n❌ Artifacts not found. Please compile contracts first:");
    console.error("   npm run compile");
  } else {
    // Read artifact
    const artifact = JSON.parse(fs.readFileSync(artifactsPath, "utf-8"));
    const abi = artifact.abi;

    // Create TypeScript file content
    const tsContent = `// Auto-generated - DO NOT EDIT
// Generated by deploy script

export const GAME2048_ABI = ${JSON.stringify(abi, null, 2)} as const;

export const GAME2048_CONTRACT_ADDRESS = "${address}" as \`0x\${string}\`;

export const game2048Contract = {
  address: GAME2048_CONTRACT_ADDRESS,
  abi: GAME2048_ABI,
} as const;
`;

    // Create output directory if it doesn't exist
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write TypeScript file to frontend
    fs.writeFileSync(outputPath, tsContent);

    console.log("\n✅ ABI and address exported to frontend:");
    console.log(`   ${outputPath}`);
  }

  console.log("\nNext steps:");
  console.log("1. Contract is ready to use in frontend");
  console.log("2. Verify the contract on Basescan:");
  if (chainId === "8453") {
    console.log(`   npm run verify:mainnet ${address}`);
  } else {
    console.log(`   npm run verify:sepolia ${address}`);
  }
  console.log("\n3. View contract on Basescan:");
  if (chainId === "8453") {
    console.log(`   https://basescan.org/address/${address}`);
  } else {
    console.log(`   https://sepolia.basescan.org/address/${address}`);
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
